let words = [
    'Turbo',
    'Discord',
    'Killex',
    'Advo',
    'Lightspeed',
    'Elli',
    'Bitchbot',
    'DeathAngel',
    'Topping',
    'Arclite',
    'Bourkadactyl',
    'Gesicht',
    'Chachi',
    'Peermafrost',
    'Cybersaurus',
    'Slushie',
    'Turbotangos',
    'Mangoboiz',
    'Overwatch',
    'Runescape',
    'Streaming',
    'Warcraft',
    'Magic',
    'Nerd',
    'Swaff',
    'Toast',
    'Lincoln',
    'Anvrar',
    'Halibread',
    'LemonLions',
    'Patti Mayonnaise',
    'Zomosis',
    'Video Games',
    'Board Games',
    'Betrayal',
    'Card Games',
    'Codenames',
    'Catan',
    'Tracer',
    'DVa',
    'McCree',
    'Widowmaker',
    'Symmetra',
    'Zarya',
    'Sombra',
    'Doomfist',
    'Mercy',
    'Mei',
    'Hanzo',
    'Winston',
    'Brigitte',
    'Genji',
    'Wrecking Ball',
    'Roadhog',
    'Moira',
    'Junkrat',
    'Pharah',
    'Torbjorn',
    'Orisa',
    'Reinhardt',
    'Sigma',
    'Ashe',
    'Bastion',
    'Echo',
    'Reaper',
    'Soldier',
    'Ana',
    'Baptiste',
    'Lucio',
    'Zenyatta',
    'Minecraft',
    'Pokemon',
    'Ironman btw',
    'Creeper',
    'Zombie',
    'Dark Souls',
    'Haval Mage',
    'The old Killex woulda done it',
    'Arknights',
    'Gatcha',
    'Alchemy Stars',
    'Factorio',
    'Satisfactory',
    'Stardew Valley',
    'Terraria',
    'ARAM',
    'Axolotl',
    'Aegwyn',
    'Lupin',
    'Scrub',
    'Moltres',
    'Zapdos',
    'Articuno',
    'Mew',
    'Mewtwo',
    'Professor Oak',
    'Ash Ketchum',
    'Pikachu',
    'Charmander',
    'Squirtle',
    'Bulbasaur',
    'Gengar',
    'Gyarados',
    'Magikarp',
    'Haunter',
    'Memes',
    'Bad Dragon',
    'Team Spirit',
    ]
